//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWeb.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JuguetesEntities : DbContext
    {
        public JuguetesEntities()
            : base("name=JuguetesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cata_Categoria> Cata_Categoria { get; set; }
        public virtual DbSet<Cata_Marca> Cata_Marca { get; set; }
        public virtual DbSet<Juguete> Juguete { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
